FROM python
 
RUN apt-get -qq update && \
    apt-get -qq install libssl-dev && \
    apt-get -qq clean && \
    apt-get -qq autoclean && \
    apt-get -qq autoremove

RUN pip install \
      bcrypt \
      pyopenssl \
      passlib \
      pymongo \
      PyJWT \
      flask \
      flask-cors \
      flask-restful
      
WORKDIR /upstaging
COPY . .

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

CMD [ "python", "./apiserver.py" ]
